name: Build Kodi Debian package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-trixie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build kodi
        run: |
          docker build -t build-kodi kodi

      - name: Extract Debian package from image
        run: |
          container_id=$(docker create build-kodi)
          docker cp "$container_id:/out/kodi-bin_21.2+dfsg-1_amd64.deb" .
          docker rm "$container_id"

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: kodi-deb
          path: ./kodi-bin_21.2+dfsg-1_amd64.deb
