name: Build Moonlight Debian package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-bookworm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build moonlight-qt
        run: |
          docker build -t build-moonlight-qt moonlight-qt

      - name: Extract Debian package from image
        run: |
          container_id=$(docker create build-moonlight-qt)
          docker cp "$container_id:/out/moonlight-qt_6.1.0-3_amd64.deb" .
          docker rm "$container_id"

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-qt-deb
          path: ./moonlight-qt_6.1.0-3_amd64.deb
